# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopoBatProfiles
                                 A QGIS plugin
 Analysis of multitemporal topo-bathymetric profiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-09
        copyright            : (C) 2026 by Enrica Vecchi
        email                : enrica.vecchi@unica.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
# -*- coding: utf-8 -*-
def classFactory(iface):
    from .topobathy_profiles import TopoBathyProfiles
    return TopoBathyProfiles(iface)
